//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTU_SINH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOA_TU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHOA_TU()
        {
            this.TU_SINH = new HashSet<TU_SINH>();
        }
    
        public int ID { get; set; }
        public string MA_KHOA_TU { get; set; }
        public string TEN_KHOA_TU { get; set; }
        public Nullable<System.DateTime> NGAY_BAT_DAU { get; set; }
        public Nullable<System.DateTime> NGAY_KET_THUC { get; set; }
        public string MIEU_TA { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TU_SINH> TU_SINH { get; set; }
    }
}
